---
- name: Create /etc/bird.conf
  copy:
    dest: '/etc/bird.conf'
    src: 'bird.conf'
    owner: root
    group: root
    mode: 0644
  notify: reconfigure bird

- name: Enable bird.service
  systemd:
    name: 'bird.service'
    enabled: yes
    masked: no
    state: started
  when: not chroot
- name: '- when in chroot'
  command: 'systemctl enable bird.service'
  when: chroot

# vim: set ts=2 sw=2 et:
