---
- name: fstab
  template:
    dest: '/etc/fstab'
    src: fstab.j2
    owner: root
    group: root
    mode: 0644
  tags:
  - fstab

- import_tasks: kernel.yml
  tags: kernel
- import_tasks: gettys.yml
  tags: gettys
- import_tasks: networkd.yml
  tags: networkd
- import_tasks: nftables.yml
  tags: nftables
- import_tasks: chrony.yml
  tags: chrony
- import_tasks: bird.yml
  tags: bird
- import_tasks: dhcpd.yml
  tags: dhcpd
- import_tasks: radius.yml
  tags: radius
  when: radius_passwords is defined
- import_tasks: named.yml
  tags: named
- import_tasks: tayga.yml
  tags: tayga
- import_tasks: avahi.yml
  tags: avahi

# vim: set ts=2 sw=2 et:
